language: node_js
node_js:
- '10'
- '12'
after_success:
- npm run coverage
- npm run coveralls
deploy:
  provider: npm
  email: pablocompagni@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: bluealba/export-web-to-pdf
